/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dao;

import java.util.Date;
import com.pm.app.dal.dto.*;
import com.pm.app.dal.exceptions.*;

public interface QuotesDao
{
	/** 
	 * Inserts a new row in the quotes table.
	 */
	public QuotesPk insert(Quotes dto) throws QuotesDaoException;

	/** 
	 * Updates a single row in the quotes table.
	 */
	public void update(QuotesPk pk, Quotes dto) throws QuotesDaoException;

	/** 
	 * Deletes a single row in the quotes table.
	 */
	public void delete(QuotesPk pk) throws QuotesDaoException;

	/** 
	 * Returns the rows from the quotes table that matches the specified primary-key value.
	 */
	public Quotes findByPrimaryKey(QuotesPk pk) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'idquotes = :idquotes'.
	 */
	public Quotes findByPrimaryKey(int idquotes) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria ''.
	 */
	public Quotes[] findAll() throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'business_partnet_id = :businessPartnetId'.
	 */
	public Quotes[] findByBusinessPartner(int businessPartnetId) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'project_id = :projectId'.
	 */
	public Quotes[] findByProjects(int projectId) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'branch_id = :branchId'.
	 */
	public Quotes[] findByBranches(int branchId) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'idquotes = :idquotes'.
	 */
	public Quotes[] findWhereIdquotesEquals(int idquotes) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'quote_date = :quoteDate'.
	 */
	public Quotes[] findWhereQuoteDateEquals(Date quoteDate) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'isTrx = :isTrx'.
	 */
	public Quotes[] findWhereIsTrxEquals(int isTrx) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'valid_to = :validTo'.
	 */
	public Quotes[] findWhereValidToEquals(Date validTo) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'business_partnet_id = :businessPartnetId'.
	 */
	public Quotes[] findWhereBusinessPartnetIdEquals(int businessPartnetId) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'tax = :tax'.
	 */
	public Quotes[] findWhereTaxEquals(double tax) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'sub_total = :subTotal'.
	 */
	public Quotes[] findWhereSubTotalEquals(double subTotal) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'grand_total = :grandTotal'.
	 */
	public Quotes[] findWhereGrandTotalEquals(double grandTotal) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'project_id = :projectId'.
	 */
	public Quotes[] findWhereProjectIdEquals(int projectId) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the criteria 'branch_id = :branchId'.
	 */
	public Quotes[] findWhereBranchIdEquals(int branchId) throws QuotesDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the quotes table that match the specified arbitrary SQL statement
	 */
	public Quotes[] findByDynamicSelect(String sql, Object[] sqlParams) throws QuotesDaoException;

	/** 
	 * Returns all rows from the quotes table that match the specified arbitrary SQL statement
	 */
	public Quotes[] findByDynamicWhere(String sql, Object[] sqlParams) throws QuotesDaoException;

}
