/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dao;

import com.pm.app.dal.dto.*;
import com.pm.app.dal.exceptions.*;

public interface SysusersDao
{
	/** 
	 * Returns all rows from the sysusers table that match the criteria ''.
	 */
	public Sysusers[] findAll() throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the criteria 'idusers = :idusers'.
	 */
	public Sysusers[] findWhereIdusersEquals(int idusers) throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the criteria 'username = :username'.
	 */
	public Sysusers[] findWhereUsernameEquals(String username) throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the criteria 'password = :password'.
	 */
	public Sysusers[] findWherePasswordEquals(String password) throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the criteria 'group_id = :groupId'.
	 */
	public Sysusers[] findWhereGroupIdEquals(int groupId) throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the criteria 'iduser_group = :iduserGroup'.
	 */
	public Sysusers[] findWhereIduserGroupEquals(int iduserGroup) throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the criteria 'name = :name'.
	 */
	public Sysusers[] findWhereNameEquals(String name) throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the criteria 'branch_id = :branchId'.
	 */
	public Sysusers[] findWhereBranchIdEquals(int branchId) throws SysusersDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the sysusers table that match the specified arbitrary SQL statement
	 */
	public Sysusers[] findByDynamicSelect(String sql, Object[] sqlParams) throws SysusersDaoException;

	/** 
	 * Returns all rows from the sysusers table that match the specified arbitrary SQL statement
	 */
	public Sysusers[] findByDynamicWhere(String sql, Object[] sqlParams) throws SysusersDaoException;

}
