/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.factory;

import java.sql.Connection;
import com.pm.app.dal.dao.*;
import com.pm.app.dal.jdbc.*;

public class UserGroupDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return UserGroupDao
	 */
	public static UserGroupDao create()
	{
		return new UserGroupDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return UserGroupDao
	 */
	public static UserGroupDao create(Connection conn)
	{
		return new UserGroupDaoImpl( conn );
	}

}
