/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.jdbc;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.dto.*;
import com.pm.app.dal.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class BusinessPartnerDaoImpl extends AbstractDAO implements BusinessPartnerDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idbusiness_partner, name, address, phone, working_as, branch_id FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idbusiness_partner, name, address, phone, working_as, branch_id ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idbusiness_partner = ?, name = ?, address = ?, phone = ?, working_as = ?, branch_id = ? WHERE idbusiness_partner = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idbusiness_partner = ?";

	/** 
	 * Index of column idbusiness_partner
	 */
	protected static final int COLUMN_IDBUSINESS_PARTNER = 1;

	/** 
	 * Index of column name
	 */
	protected static final int COLUMN_NAME = 2;

	/** 
	 * Index of column address
	 */
	protected static final int COLUMN_ADDRESS = 3;

	/** 
	 * Index of column phone
	 */
	protected static final int COLUMN_PHONE = 4;

	/** 
	 * Index of column working_as
	 */
	protected static final int COLUMN_WORKING_AS = 5;

	/** 
	 * Index of column branch_id
	 */
	protected static final int COLUMN_BRANCH_ID = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column idbusiness_partner
	 */
	protected static final int PK_COLUMN_IDBUSINESS_PARTNER = 1;

	/** 
	 * Inserts a new row in the business_partner table.
	 */
	public BusinessPartnerPk insert(BusinessPartner dto) throws BusinessPartnerDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdbusinessPartner() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getAddress() );
			stmt.setString( index++, dto.getPhone() );
			if (dto.isWorkingAsNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getWorkingAs() );
			}
		
			if (dto.isBranchIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getBranchId() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdbusinessPartner( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusinessPartnerDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the business_partner table.
	 */
	public void update(BusinessPartnerPk pk, BusinessPartner dto) throws BusinessPartnerDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdbusinessPartner() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getAddress() );
			stmt.setString( index++, dto.getPhone() );
			if (dto.isWorkingAsNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getWorkingAs() );
			}
		
			if (dto.isBranchIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getBranchId() );
			}
		
			stmt.setInt( 7, pk.getIdbusinessPartner() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusinessPartnerDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the business_partner table.
	 */
	public void delete(BusinessPartnerPk pk) throws BusinessPartnerDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdbusinessPartner() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusinessPartnerDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the business_partner table that matches the specified primary-key value.
	 */
	public BusinessPartner findByPrimaryKey(BusinessPartnerPk pk) throws BusinessPartnerDaoException
	{
		return findByPrimaryKey( pk.getIdbusinessPartner() );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'idbusiness_partner = :idbusinessPartner'.
	 */
	public BusinessPartner findByPrimaryKey(int idbusinessPartner) throws BusinessPartnerDaoException
	{
		BusinessPartner ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idbusiness_partner = ?", new Object[] {  new Integer(idbusinessPartner) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria ''.
	 */
	public BusinessPartner[] findAll() throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idbusiness_partner", null );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'branch_id = :branchId'.
	 */
	public BusinessPartner[] findByBranches(int branchId) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE branch_id = ?", new Object[] {  new Integer(branchId) } );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'working_as = :workingAs'.
	 */
	public BusinessPartner[] findByBusinessPartnerType(int workingAs) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE working_as = ?", new Object[] {  new Integer(workingAs) } );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'idbusiness_partner = :idbusinessPartner'.
	 */
	public BusinessPartner[] findWhereIdbusinessPartnerEquals(int idbusinessPartner) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idbusiness_partner = ? ORDER BY idbusiness_partner", new Object[] {  new Integer(idbusinessPartner) } );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'name = :name'.
	 */
	public BusinessPartner[] findWhereNameEquals(String name) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE name = ? ORDER BY name", new Object[] { name } );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'address = :address'.
	 */
	public BusinessPartner[] findWhereAddressEquals(String address) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE address = ? ORDER BY address", new Object[] { address } );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'phone = :phone'.
	 */
	public BusinessPartner[] findWherePhoneEquals(String phone) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE phone = ? ORDER BY phone", new Object[] { phone } );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'working_as = :workingAs'.
	 */
	public BusinessPartner[] findWhereWorkingAsEquals(int workingAs) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE working_as = ? ORDER BY working_as", new Object[] {  new Integer(workingAs) } );
	}

	/** 
	 * Returns all rows from the business_partner table that match the criteria 'branch_id = :branchId'.
	 */
	public BusinessPartner[] findWhereBranchIdEquals(int branchId) throws BusinessPartnerDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE branch_id = ? ORDER BY branch_id", new Object[] {  new Integer(branchId) } );
	}

	/**
	 * Method 'BusinessPartnerDaoImpl'
	 * 
	 */
	public BusinessPartnerDaoImpl()
	{
	}

	/**
	 * Method 'BusinessPartnerDaoImpl'
	 * 
	 * @param userConn
	 */
	public BusinessPartnerDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "constructions_web.business_partner";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected BusinessPartner fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			BusinessPartner dto = new BusinessPartner();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected BusinessPartner[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			BusinessPartner dto = new BusinessPartner();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		BusinessPartner ret[] = new BusinessPartner[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(BusinessPartner dto, ResultSet rs) throws SQLException
	{
		dto.setIdbusinessPartner( rs.getInt( COLUMN_IDBUSINESS_PARTNER ) );
		dto.setName( rs.getString( COLUMN_NAME ) );
		dto.setAddress( rs.getString( COLUMN_ADDRESS ) );
		dto.setPhone( rs.getString( COLUMN_PHONE ) );
		dto.setWorkingAs( rs.getInt( COLUMN_WORKING_AS ) );
		if (rs.wasNull()) {
			dto.setWorkingAsNull( true );
		}
		
		dto.setBranchId( rs.getInt( COLUMN_BRANCH_ID ) );
		if (rs.wasNull()) {
			dto.setBranchIdNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(BusinessPartner dto)
	{
	}

	/** 
	 * Returns all rows from the business_partner table that match the specified arbitrary SQL statement
	 */
	public BusinessPartner[] findByDynamicSelect(String sql, Object[] sqlParams) throws BusinessPartnerDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusinessPartnerDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the business_partner table that match the specified arbitrary SQL statement
	 */
	public BusinessPartner[] findByDynamicWhere(String sql, Object[] sqlParams) throws BusinessPartnerDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new BusinessPartnerDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
