/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.jdbc;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.dto.*;
import com.pm.app.dal.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class StaticProjectPhasesDaoImpl extends AbstractDAO implements StaticProjectPhasesDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idstatic_project_phases, name, description, type FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idstatic_project_phases, name, description, type ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idstatic_project_phases = ?, name = ?, description = ?, type = ? WHERE idstatic_project_phases = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idstatic_project_phases = ?";

	/** 
	 * Index of column idstatic_project_phases
	 */
	protected static final int COLUMN_IDSTATIC_PROJECT_PHASES = 1;

	/** 
	 * Index of column name
	 */
	protected static final int COLUMN_NAME = 2;

	/** 
	 * Index of column description
	 */
	protected static final int COLUMN_DESCRIPTION = 3;

	/** 
	 * Index of column type
	 */
	protected static final int COLUMN_TYPE = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column idstatic_project_phases
	 */
	protected static final int PK_COLUMN_IDSTATIC_PROJECT_PHASES = 1;

	/** 
	 * Inserts a new row in the static_project_phases table.
	 */
	public StaticProjectPhasesPk insert(StaticProjectPhases dto) throws StaticProjectPhasesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdstaticProjectPhases() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getDescription() );
			if (dto.isTypeNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getType() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdstaticProjectPhases( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaticProjectPhasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the static_project_phases table.
	 */
	public void update(StaticProjectPhasesPk pk, StaticProjectPhases dto) throws StaticProjectPhasesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdstaticProjectPhases() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getDescription() );
			if (dto.isTypeNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getType() );
			}
		
			stmt.setInt( 5, pk.getIdstaticProjectPhases() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaticProjectPhasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the static_project_phases table.
	 */
	public void delete(StaticProjectPhasesPk pk) throws StaticProjectPhasesDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdstaticProjectPhases() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaticProjectPhasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the static_project_phases table that matches the specified primary-key value.
	 */
	public StaticProjectPhases findByPrimaryKey(StaticProjectPhasesPk pk) throws StaticProjectPhasesDaoException
	{
		return findByPrimaryKey( pk.getIdstaticProjectPhases() );
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the criteria 'idstatic_project_phases = :idstaticProjectPhases'.
	 */
	public StaticProjectPhases findByPrimaryKey(int idstaticProjectPhases) throws StaticProjectPhasesDaoException
	{
		StaticProjectPhases ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idstatic_project_phases = ?", new Object[] {  new Integer(idstaticProjectPhases) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the criteria ''.
	 */
	public StaticProjectPhases[] findAll() throws StaticProjectPhasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idstatic_project_phases", null );
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the criteria 'type = :type'.
	 */
	public StaticProjectPhases[] findByProjectType(int type) throws StaticProjectPhasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE type = ?", new Object[] {  new Integer(type) } );
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the criteria 'idstatic_project_phases = :idstaticProjectPhases'.
	 */
	public StaticProjectPhases[] findWhereIdstaticProjectPhasesEquals(int idstaticProjectPhases) throws StaticProjectPhasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idstatic_project_phases = ? ORDER BY idstatic_project_phases", new Object[] {  new Integer(idstaticProjectPhases) } );
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the criteria 'name = :name'.
	 */
	public StaticProjectPhases[] findWhereNameEquals(String name) throws StaticProjectPhasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE name = ? ORDER BY name", new Object[] { name } );
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the criteria 'description = :description'.
	 */
	public StaticProjectPhases[] findWhereDescriptionEquals(String description) throws StaticProjectPhasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE description = ? ORDER BY description", new Object[] { description } );
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the criteria 'type = :type'.
	 */
	public StaticProjectPhases[] findWhereTypeEquals(int type) throws StaticProjectPhasesDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE type = ? ORDER BY type", new Object[] {  new Integer(type) } );
	}

	/**
	 * Method 'StaticProjectPhasesDaoImpl'
	 * 
	 */
	public StaticProjectPhasesDaoImpl()
	{
	}

	/**
	 * Method 'StaticProjectPhasesDaoImpl'
	 * 
	 * @param userConn
	 */
	public StaticProjectPhasesDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "constructions_web.static_project_phases";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected StaticProjectPhases fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			StaticProjectPhases dto = new StaticProjectPhases();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected StaticProjectPhases[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			StaticProjectPhases dto = new StaticProjectPhases();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		StaticProjectPhases ret[] = new StaticProjectPhases[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(StaticProjectPhases dto, ResultSet rs) throws SQLException
	{
		dto.setIdstaticProjectPhases( rs.getInt( COLUMN_IDSTATIC_PROJECT_PHASES ) );
		dto.setName( rs.getString( COLUMN_NAME ) );
		dto.setDescription( rs.getString( COLUMN_DESCRIPTION ) );
		dto.setType( rs.getInt( COLUMN_TYPE ) );
		if (rs.wasNull()) {
			dto.setTypeNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(StaticProjectPhases dto)
	{
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the specified arbitrary SQL statement
	 */
	public StaticProjectPhases[] findByDynamicSelect(String sql, Object[] sqlParams) throws StaticProjectPhasesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaticProjectPhasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the static_project_phases table that match the specified arbitrary SQL statement
	 */
	public StaticProjectPhases[] findByDynamicWhere(String sql, Object[] sqlParams) throws StaticProjectPhasesDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaticProjectPhasesDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
