/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.jdbc;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.dto.*;
import com.pm.app.dal.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TaskManagementDaoImpl extends AbstractDAO implements TaskManagementDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idtask_management, task_id, business_partnet_id FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idtask_management, task_id, business_partnet_id ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idtask_management = ?, task_id = ?, business_partnet_id = ? WHERE idtask_management = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idtask_management = ?";

	/** 
	 * Index of column idtask_management
	 */
	protected static final int COLUMN_IDTASK_MANAGEMENT = 1;

	/** 
	 * Index of column task_id
	 */
	protected static final int COLUMN_TASK_ID = 2;

	/** 
	 * Index of column business_partnet_id
	 */
	protected static final int COLUMN_BUSINESS_PARTNET_ID = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column idtask_management
	 */
	protected static final int PK_COLUMN_IDTASK_MANAGEMENT = 1;

	/** 
	 * Inserts a new row in the task_management table.
	 */
	public TaskManagementPk insert(TaskManagement dto) throws TaskManagementDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdtaskManagement() );
			if (dto.isTaskIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getTaskId() );
			}
		
			if (dto.isBusinessPartnetIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getBusinessPartnetId() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdtaskManagement( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TaskManagementDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the task_management table.
	 */
	public void update(TaskManagementPk pk, TaskManagement dto) throws TaskManagementDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdtaskManagement() );
			if (dto.isTaskIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getTaskId() );
			}
		
			if (dto.isBusinessPartnetIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getBusinessPartnetId() );
			}
		
			stmt.setInt( 4, pk.getIdtaskManagement() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TaskManagementDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the task_management table.
	 */
	public void delete(TaskManagementPk pk) throws TaskManagementDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdtaskManagement() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TaskManagementDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the task_management table that matches the specified primary-key value.
	 */
	public TaskManagement findByPrimaryKey(TaskManagementPk pk) throws TaskManagementDaoException
	{
		return findByPrimaryKey( pk.getIdtaskManagement() );
	}

	/** 
	 * Returns all rows from the task_management table that match the criteria 'idtask_management = :idtaskManagement'.
	 */
	public TaskManagement findByPrimaryKey(int idtaskManagement) throws TaskManagementDaoException
	{
		TaskManagement ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idtask_management = ?", new Object[] {  new Integer(idtaskManagement) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the task_management table that match the criteria ''.
	 */
	public TaskManagement[] findAll() throws TaskManagementDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idtask_management", null );
	}

	/** 
	 * Returns all rows from the task_management table that match the criteria 'business_partnet_id = :businessPartnetId'.
	 */
	public TaskManagement[] findByBusinessPartner(int businessPartnetId) throws TaskManagementDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE business_partnet_id = ?", new Object[] {  new Integer(businessPartnetId) } );
	}

	/** 
	 * Returns all rows from the task_management table that match the criteria 'task_id = :taskId'.
	 */
	public TaskManagement[] findByTasks(int taskId) throws TaskManagementDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE task_id = ?", new Object[] {  new Integer(taskId) } );
	}

	/** 
	 * Returns all rows from the task_management table that match the criteria 'idtask_management = :idtaskManagement'.
	 */
	public TaskManagement[] findWhereIdtaskManagementEquals(int idtaskManagement) throws TaskManagementDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idtask_management = ? ORDER BY idtask_management", new Object[] {  new Integer(idtaskManagement) } );
	}

	/** 
	 * Returns all rows from the task_management table that match the criteria 'task_id = :taskId'.
	 */
	public TaskManagement[] findWhereTaskIdEquals(int taskId) throws TaskManagementDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE task_id = ? ORDER BY task_id", new Object[] {  new Integer(taskId) } );
	}

	/** 
	 * Returns all rows from the task_management table that match the criteria 'business_partnet_id = :businessPartnetId'.
	 */
	public TaskManagement[] findWhereBusinessPartnetIdEquals(int businessPartnetId) throws TaskManagementDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE business_partnet_id = ? ORDER BY business_partnet_id", new Object[] {  new Integer(businessPartnetId) } );
	}

	/**
	 * Method 'TaskManagementDaoImpl'
	 * 
	 */
	public TaskManagementDaoImpl()
	{
	}

	/**
	 * Method 'TaskManagementDaoImpl'
	 * 
	 * @param userConn
	 */
	public TaskManagementDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "constructions_web.task_management";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected TaskManagement fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			TaskManagement dto = new TaskManagement();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected TaskManagement[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			TaskManagement dto = new TaskManagement();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		TaskManagement ret[] = new TaskManagement[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(TaskManagement dto, ResultSet rs) throws SQLException
	{
		dto.setIdtaskManagement( rs.getInt( COLUMN_IDTASK_MANAGEMENT ) );
		dto.setTaskId( rs.getInt( COLUMN_TASK_ID ) );
		if (rs.wasNull()) {
			dto.setTaskIdNull( true );
		}
		
		dto.setBusinessPartnetId( rs.getInt( COLUMN_BUSINESS_PARTNET_ID ) );
		if (rs.wasNull()) {
			dto.setBusinessPartnetIdNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(TaskManagement dto)
	{
	}

	/** 
	 * Returns all rows from the task_management table that match the specified arbitrary SQL statement
	 */
	public TaskManagement[] findByDynamicSelect(String sql, Object[] sqlParams) throws TaskManagementDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TaskManagementDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the task_management table that match the specified arbitrary SQL statement
	 */
	public TaskManagement[] findByDynamicWhere(String sql, Object[] sqlParams) throws TaskManagementDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TaskManagementDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
