/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.jdbc;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import java.util.Date;
import com.pm.app.dal.dto.*;
import com.pm.app.dal.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TasksDaoImpl extends AbstractDAO implements TasksDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idtasks, name, description, start_date, end_date, phase_id, status FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idtasks, name, description, start_date, end_date, phase_id, status ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idtasks = ?, name = ?, description = ?, start_date = ?, end_date = ?, phase_id = ?, status = ? WHERE idtasks = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idtasks = ?";

	/** 
	 * Index of column idtasks
	 */
	protected static final int COLUMN_IDTASKS = 1;

	/** 
	 * Index of column name
	 */
	protected static final int COLUMN_NAME = 2;

	/** 
	 * Index of column description
	 */
	protected static final int COLUMN_DESCRIPTION = 3;

	/** 
	 * Index of column start_date
	 */
	protected static final int COLUMN_START_DATE = 4;

	/** 
	 * Index of column end_date
	 */
	protected static final int COLUMN_END_DATE = 5;

	/** 
	 * Index of column phase_id
	 */
	protected static final int COLUMN_PHASE_ID = 6;

	/** 
	 * Index of column status
	 */
	protected static final int COLUMN_STATUS = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column idtasks
	 */
	protected static final int PK_COLUMN_IDTASKS = 1;

	/** 
	 * Inserts a new row in the tasks table.
	 */
	public TasksPk insert(Tasks dto) throws TasksDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdtasks() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getDescription() );
			stmt.setDate(index++, dto.getStartDate()==null ? null : new java.sql.Date( dto.getStartDate().getTime() ) );
			stmt.setDate(index++, dto.getEndDate()==null ? null : new java.sql.Date( dto.getEndDate().getTime() ) );
			if (dto.isPhaseIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getPhaseId() );
			}
		
			if (dto.isStatusNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getStatus() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdtasks( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TasksDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the tasks table.
	 */
	public void update(TasksPk pk, Tasks dto) throws TasksDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdtasks() );
			stmt.setString( index++, dto.getName() );
			stmt.setString( index++, dto.getDescription() );
			stmt.setDate(index++, dto.getStartDate()==null ? null : new java.sql.Date( dto.getStartDate().getTime() ) );
			stmt.setDate(index++, dto.getEndDate()==null ? null : new java.sql.Date( dto.getEndDate().getTime() ) );
			if (dto.isPhaseIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getPhaseId() );
			}
		
			if (dto.isStatusNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getStatus() );
			}
		
			stmt.setInt( 8, pk.getIdtasks() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TasksDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the tasks table.
	 */
	public void delete(TasksPk pk) throws TasksDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdtasks() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TasksDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the tasks table that matches the specified primary-key value.
	 */
	public Tasks findByPrimaryKey(TasksPk pk) throws TasksDaoException
	{
		return findByPrimaryKey( pk.getIdtasks() );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'idtasks = :idtasks'.
	 */
	public Tasks findByPrimaryKey(int idtasks) throws TasksDaoException
	{
		Tasks ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idtasks = ?", new Object[] {  new Integer(idtasks) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria ''.
	 */
	public Tasks[] findAll() throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idtasks", null );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'status = :status'.
	 */
	public Tasks[] findByWorkingStatus(int status) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE status = ?", new Object[] {  new Integer(status) } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'phase_id = :phaseId'.
	 */
	public Tasks[] findByProjectPhases(int phaseId) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE phase_id = ?", new Object[] {  new Integer(phaseId) } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'idtasks = :idtasks'.
	 */
	public Tasks[] findWhereIdtasksEquals(int idtasks) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idtasks = ? ORDER BY idtasks", new Object[] {  new Integer(idtasks) } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'name = :name'.
	 */
	public Tasks[] findWhereNameEquals(String name) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE name = ? ORDER BY name", new Object[] { name } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'description = :description'.
	 */
	public Tasks[] findWhereDescriptionEquals(String description) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE description = ? ORDER BY description", new Object[] { description } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'start_date = :startDate'.
	 */
	public Tasks[] findWhereStartDateEquals(Date startDate) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE start_date = ? ORDER BY start_date", new Object[] { startDate==null ? null : new java.sql.Date( startDate.getTime() ) } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'end_date = :endDate'.
	 */
	public Tasks[] findWhereEndDateEquals(Date endDate) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE end_date = ? ORDER BY end_date", new Object[] { endDate==null ? null : new java.sql.Date( endDate.getTime() ) } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'phase_id = :phaseId'.
	 */
	public Tasks[] findWherePhaseIdEquals(int phaseId) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE phase_id = ? ORDER BY phase_id", new Object[] {  new Integer(phaseId) } );
	}

	/** 
	 * Returns all rows from the tasks table that match the criteria 'status = :status'.
	 */
	public Tasks[] findWhereStatusEquals(int status) throws TasksDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE status = ? ORDER BY status", new Object[] {  new Integer(status) } );
	}

	/**
	 * Method 'TasksDaoImpl'
	 * 
	 */
	public TasksDaoImpl()
	{
	}

	/**
	 * Method 'TasksDaoImpl'
	 * 
	 * @param userConn
	 */
	public TasksDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "constructions_web.tasks";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Tasks fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Tasks dto = new Tasks();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Tasks[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Tasks dto = new Tasks();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Tasks ret[] = new Tasks[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Tasks dto, ResultSet rs) throws SQLException
	{
		dto.setIdtasks( rs.getInt( COLUMN_IDTASKS ) );
		dto.setName( rs.getString( COLUMN_NAME ) );
		dto.setDescription( rs.getString( COLUMN_DESCRIPTION ) );
		dto.setStartDate( rs.getDate(COLUMN_START_DATE ) );
		dto.setEndDate( rs.getDate(COLUMN_END_DATE ) );
		dto.setPhaseId( rs.getInt( COLUMN_PHASE_ID ) );
		if (rs.wasNull()) {
			dto.setPhaseIdNull( true );
		}
		
		dto.setStatus( rs.getInt( COLUMN_STATUS ) );
		if (rs.wasNull()) {
			dto.setStatusNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Tasks dto)
	{
	}

	/** 
	 * Returns all rows from the tasks table that match the specified arbitrary SQL statement
	 */
	public Tasks[] findByDynamicSelect(String sql, Object[] sqlParams) throws TasksDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TasksDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the tasks table that match the specified arbitrary SQL statement
	 */
	public Tasks[] findByDynamicWhere(String sql, Object[] sqlParams) throws TasksDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TasksDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
