/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the branches table.
 */
public class BranchesPk implements Serializable
{
	protected int idbranches;

	/** 
	 * This attribute represents whether the primitive attribute idbranches is null.
	 */
	protected boolean idbranchesNull;

	/** 
	 * Sets the value of idbranches
	 */
	public void setIdbranches(int idbranches)
	{
		this.idbranches = idbranches;
	}

	/** 
	 * Gets the value of idbranches
	 */
	public int getIdbranches()
	{
		return idbranches;
	}

	/**
	 * Method 'BranchesPk'
	 * 
	 */
	public BranchesPk()
	{
	}

	/**
	 * Method 'BranchesPk'
	 * 
	 * @param idbranches
	 */
	public BranchesPk(final int idbranches)
	{
		this.idbranches = idbranches;
	}

	/** 
	 * Sets the value of idbranchesNull
	 */
	public void setIdbranchesNull(boolean idbranchesNull)
	{
		this.idbranchesNull = idbranchesNull;
	}

	/** 
	 * Gets the value of idbranchesNull
	 */
	public boolean isIdbranchesNull()
	{
		return idbranchesNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BranchesPk)) {
			return false;
		}
		
		final BranchesPk _cast = (BranchesPk) _other;
		if (idbranches != _cast.idbranches) {
			return false;
		}
		
		if (idbranchesNull != _cast.idbranchesNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idbranches;
		_hashCode = 29 * _hashCode + (idbranchesNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.BranchesPk: " );
		ret.append( "idbranches=" + idbranches );
		return ret.toString();
	}

}
