/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the business_partner_type table.
 */
public class BusinessPartnerTypePk implements Serializable
{
	protected int idbusinessPartnerType;

	/** 
	 * This attribute represents whether the primitive attribute idbusinessPartnerType is null.
	 */
	protected boolean idbusinessPartnerTypeNull;

	/** 
	 * Sets the value of idbusinessPartnerType
	 */
	public void setIdbusinessPartnerType(int idbusinessPartnerType)
	{
		this.idbusinessPartnerType = idbusinessPartnerType;
	}

	/** 
	 * Gets the value of idbusinessPartnerType
	 */
	public int getIdbusinessPartnerType()
	{
		return idbusinessPartnerType;
	}

	/**
	 * Method 'BusinessPartnerTypePk'
	 * 
	 */
	public BusinessPartnerTypePk()
	{
	}

	/**
	 * Method 'BusinessPartnerTypePk'
	 * 
	 * @param idbusinessPartnerType
	 */
	public BusinessPartnerTypePk(final int idbusinessPartnerType)
	{
		this.idbusinessPartnerType = idbusinessPartnerType;
	}

	/** 
	 * Sets the value of idbusinessPartnerTypeNull
	 */
	public void setIdbusinessPartnerTypeNull(boolean idbusinessPartnerTypeNull)
	{
		this.idbusinessPartnerTypeNull = idbusinessPartnerTypeNull;
	}

	/** 
	 * Gets the value of idbusinessPartnerTypeNull
	 */
	public boolean isIdbusinessPartnerTypeNull()
	{
		return idbusinessPartnerTypeNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BusinessPartnerTypePk)) {
			return false;
		}
		
		final BusinessPartnerTypePk _cast = (BusinessPartnerTypePk) _other;
		if (idbusinessPartnerType != _cast.idbusinessPartnerType) {
			return false;
		}
		
		if (idbusinessPartnerTypeNull != _cast.idbusinessPartnerTypeNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idbusinessPartnerType;
		_hashCode = 29 * _hashCode + (idbusinessPartnerTypeNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.BusinessPartnerTypePk: " );
		ret.append( "idbusinessPartnerType=" + idbusinessPartnerType );
		return ret.toString();
	}

}
