/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class BusinessPartnerType implements Serializable
{
	/** 
	 * This attribute maps to the column idbusiness_partner_type in the business_partner_type table.
	 */
	protected int idbusinessPartnerType;

	/** 
	 * This attribute maps to the column type in the business_partner_type table.
	 */
	protected String type;

	/**
	 * Method 'BusinessPartnerType'
	 * 
	 */
	public BusinessPartnerType()
	{
	}

	/**
	 * Method 'getIdbusinessPartnerType'
	 * 
	 * @return int
	 */
	public int getIdbusinessPartnerType()
	{
		return idbusinessPartnerType;
	}

	/**
	 * Method 'setIdbusinessPartnerType'
	 * 
	 * @param idbusinessPartnerType
	 */
	public void setIdbusinessPartnerType(int idbusinessPartnerType)
	{
		this.idbusinessPartnerType = idbusinessPartnerType;
	}

	/**
	 * Method 'getType'
	 * 
	 * @return String
	 */
	public String getType()
	{
		return type;
	}

	/**
	 * Method 'setType'
	 * 
	 * @param type
	 */
	public void setType(String type)
	{
		this.type = type;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BusinessPartnerType)) {
			return false;
		}
		
		final BusinessPartnerType _cast = (BusinessPartnerType) _other;
		if (idbusinessPartnerType != _cast.idbusinessPartnerType) {
			return false;
		}
		
		if (type == null ? _cast.type != type : !type.equals( _cast.type )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idbusinessPartnerType;
		if (type != null) {
			_hashCode = 29 * _hashCode + type.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return BusinessPartnerTypePk
	 */
	public BusinessPartnerTypePk createPk()
	{
		return new BusinessPartnerTypePk(idbusinessPartnerType);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.BusinessPartnerType: " );
		ret.append( "idbusinessPartnerType=" + idbusinessPartnerType );
		ret.append( ", type=" + type );
		return ret.toString();
	}

}
