/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the business_partner table.
 */
public class BusinessPartnerPk implements Serializable
{
	protected int idbusinessPartner;

	/** 
	 * This attribute represents whether the primitive attribute idbusinessPartner is null.
	 */
	protected boolean idbusinessPartnerNull;

	/** 
	 * Sets the value of idbusinessPartner
	 */
	public void setIdbusinessPartner(int idbusinessPartner)
	{
		this.idbusinessPartner = idbusinessPartner;
	}

	/** 
	 * Gets the value of idbusinessPartner
	 */
	public int getIdbusinessPartner()
	{
		return idbusinessPartner;
	}

	/**
	 * Method 'BusinessPartnerPk'
	 * 
	 */
	public BusinessPartnerPk()
	{
	}

	/**
	 * Method 'BusinessPartnerPk'
	 * 
	 * @param idbusinessPartner
	 */
	public BusinessPartnerPk(final int idbusinessPartner)
	{
		this.idbusinessPartner = idbusinessPartner;
	}

	/** 
	 * Sets the value of idbusinessPartnerNull
	 */
	public void setIdbusinessPartnerNull(boolean idbusinessPartnerNull)
	{
		this.idbusinessPartnerNull = idbusinessPartnerNull;
	}

	/** 
	 * Gets the value of idbusinessPartnerNull
	 */
	public boolean isIdbusinessPartnerNull()
	{
		return idbusinessPartnerNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BusinessPartnerPk)) {
			return false;
		}
		
		final BusinessPartnerPk _cast = (BusinessPartnerPk) _other;
		if (idbusinessPartner != _cast.idbusinessPartner) {
			return false;
		}
		
		if (idbusinessPartnerNull != _cast.idbusinessPartnerNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idbusinessPartner;
		_hashCode = 29 * _hashCode + (idbusinessPartnerNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.BusinessPartnerPk: " );
		ret.append( "idbusinessPartner=" + idbusinessPartner );
		return ret.toString();
	}

}
