/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the invoices table.
 */
public class InvoicesPk implements Serializable
{
	protected int idinvoice;

	/** 
	 * This attribute represents whether the primitive attribute idinvoice is null.
	 */
	protected boolean idinvoiceNull;

	/** 
	 * Sets the value of idinvoice
	 */
	public void setIdinvoice(int idinvoice)
	{
		this.idinvoice = idinvoice;
	}

	/** 
	 * Gets the value of idinvoice
	 */
	public int getIdinvoice()
	{
		return idinvoice;
	}

	/**
	 * Method 'InvoicesPk'
	 * 
	 */
	public InvoicesPk()
	{
	}

	/**
	 * Method 'InvoicesPk'
	 * 
	 * @param idinvoice
	 */
	public InvoicesPk(final int idinvoice)
	{
		this.idinvoice = idinvoice;
	}

	/** 
	 * Sets the value of idinvoiceNull
	 */
	public void setIdinvoiceNull(boolean idinvoiceNull)
	{
		this.idinvoiceNull = idinvoiceNull;
	}

	/** 
	 * Gets the value of idinvoiceNull
	 */
	public boolean isIdinvoiceNull()
	{
		return idinvoiceNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InvoicesPk)) {
			return false;
		}
		
		final InvoicesPk _cast = (InvoicesPk) _other;
		if (idinvoice != _cast.idinvoice) {
			return false;
		}
		
		if (idinvoiceNull != _cast.idinvoiceNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idinvoice;
		_hashCode = 29 * _hashCode + (idinvoiceNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.InvoicesPk: " );
		ret.append( "idinvoice=" + idinvoice );
		return ret.toString();
	}

}
