/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the items table.
 */
public class ItemsPk implements Serializable
{
	protected int iditems;

	/** 
	 * This attribute represents whether the primitive attribute iditems is null.
	 */
	protected boolean iditemsNull;

	/** 
	 * Sets the value of iditems
	 */
	public void setIditems(int iditems)
	{
		this.iditems = iditems;
	}

	/** 
	 * Gets the value of iditems
	 */
	public int getIditems()
	{
		return iditems;
	}

	/**
	 * Method 'ItemsPk'
	 * 
	 */
	public ItemsPk()
	{
	}

	/**
	 * Method 'ItemsPk'
	 * 
	 * @param iditems
	 */
	public ItemsPk(final int iditems)
	{
		this.iditems = iditems;
	}

	/** 
	 * Sets the value of iditemsNull
	 */
	public void setIditemsNull(boolean iditemsNull)
	{
		this.iditemsNull = iditemsNull;
	}

	/** 
	 * Gets the value of iditemsNull
	 */
	public boolean isIditemsNull()
	{
		return iditemsNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemsPk)) {
			return false;
		}
		
		final ItemsPk _cast = (ItemsPk) _other;
		if (iditems != _cast.iditems) {
			return false;
		}
		
		if (iditemsNull != _cast.iditemsNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + iditems;
		_hashCode = 29 * _hashCode + (iditemsNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.ItemsPk: " );
		ret.append( "iditems=" + iditems );
		return ret.toString();
	}

}
