/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Items implements Serializable
{
	/** 
	 * This attribute maps to the column iditems in the items table.
	 */
	protected int iditems;

	/** 
	 * This attribute maps to the column name in the items table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column quantity in the items table.
	 */
	protected int quantity;

	/** 
	 * This attribute represents whether the primitive attribute quantity is null.
	 */
	protected boolean quantityNull = true;

	/** 
	 * This attribute maps to the column unit_id in the items table.
	 */
	protected int unitId;

	/** 
	 * This attribute represents whether the primitive attribute unitId is null.
	 */
	protected boolean unitIdNull = true;

	/** 
	 * This attribute maps to the column branch_id in the items table.
	 */
	protected int branchId;

	/** 
	 * This attribute represents whether the primitive attribute branchId is null.
	 */
	protected boolean branchIdNull = true;

	/** 
	 * This attribute maps to the column category_id in the items table.
	 */
	protected int categoryId;

	/** 
	 * This attribute represents whether the primitive attribute categoryId is null.
	 */
	protected boolean categoryIdNull = true;

	/**
	 * Method 'Items'
	 * 
	 */
	public Items()
	{
	}

	/**
	 * Method 'getIditems'
	 * 
	 * @return int
	 */
	public int getIditems()
	{
		return iditems;
	}

	/**
	 * Method 'setIditems'
	 * 
	 * @param iditems
	 */
	public void setIditems(int iditems)
	{
		this.iditems = iditems;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getQuantity'
	 * 
	 * @return int
	 */
	public int getQuantity()
	{
		return quantity;
	}

	/**
	 * Method 'setQuantity'
	 * 
	 * @param quantity
	 */
	public void setQuantity(int quantity)
	{
		this.quantity = quantity;
		this.quantityNull = false;
	}

	/**
	 * Method 'setQuantityNull'
	 * 
	 * @param value
	 */
	public void setQuantityNull(boolean value)
	{
		this.quantityNull = value;
	}

	/**
	 * Method 'isQuantityNull'
	 * 
	 * @return boolean
	 */
	public boolean isQuantityNull()
	{
		return quantityNull;
	}

	/**
	 * Method 'getUnitId'
	 * 
	 * @return int
	 */
	public int getUnitId()
	{
		return unitId;
	}

	/**
	 * Method 'setUnitId'
	 * 
	 * @param unitId
	 */
	public void setUnitId(int unitId)
	{
		this.unitId = unitId;
		this.unitIdNull = false;
	}

	/**
	 * Method 'setUnitIdNull'
	 * 
	 * @param value
	 */
	public void setUnitIdNull(boolean value)
	{
		this.unitIdNull = value;
	}

	/**
	 * Method 'isUnitIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isUnitIdNull()
	{
		return unitIdNull;
	}

	/**
	 * Method 'getBranchId'
	 * 
	 * @return int
	 */
	public int getBranchId()
	{
		return branchId;
	}

	/**
	 * Method 'setBranchId'
	 * 
	 * @param branchId
	 */
	public void setBranchId(int branchId)
	{
		this.branchId = branchId;
		this.branchIdNull = false;
	}

	/**
	 * Method 'setBranchIdNull'
	 * 
	 * @param value
	 */
	public void setBranchIdNull(boolean value)
	{
		this.branchIdNull = value;
	}

	/**
	 * Method 'isBranchIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBranchIdNull()
	{
		return branchIdNull;
	}

	/**
	 * Method 'getCategoryId'
	 * 
	 * @return int
	 */
	public int getCategoryId()
	{
		return categoryId;
	}

	/**
	 * Method 'setCategoryId'
	 * 
	 * @param categoryId
	 */
	public void setCategoryId(int categoryId)
	{
		this.categoryId = categoryId;
		this.categoryIdNull = false;
	}

	/**
	 * Method 'setCategoryIdNull'
	 * 
	 * @param value
	 */
	public void setCategoryIdNull(boolean value)
	{
		this.categoryIdNull = value;
	}

	/**
	 * Method 'isCategoryIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isCategoryIdNull()
	{
		return categoryIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Items)) {
			return false;
		}
		
		final Items _cast = (Items) _other;
		if (iditems != _cast.iditems) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (quantity != _cast.quantity) {
			return false;
		}
		
		if (quantityNull != _cast.quantityNull) {
			return false;
		}
		
		if (unitId != _cast.unitId) {
			return false;
		}
		
		if (unitIdNull != _cast.unitIdNull) {
			return false;
		}
		
		if (branchId != _cast.branchId) {
			return false;
		}
		
		if (branchIdNull != _cast.branchIdNull) {
			return false;
		}
		
		if (categoryId != _cast.categoryId) {
			return false;
		}
		
		if (categoryIdNull != _cast.categoryIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + iditems;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + quantity;
		_hashCode = 29 * _hashCode + (quantityNull ? 1 : 0);
		_hashCode = 29 * _hashCode + unitId;
		_hashCode = 29 * _hashCode + (unitIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + branchId;
		_hashCode = 29 * _hashCode + (branchIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + categoryId;
		_hashCode = 29 * _hashCode + (categoryIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemsPk
	 */
	public ItemsPk createPk()
	{
		return new ItemsPk(iditems);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.Items: " );
		ret.append( "iditems=" + iditems );
		ret.append( ", name=" + name );
		ret.append( ", quantity=" + quantity );
		ret.append( ", unitId=" + unitId );
		ret.append( ", branchId=" + branchId );
		ret.append( ", categoryId=" + categoryId );
		return ret.toString();
	}

}
