/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the projects table.
 */
public class ProjectsPk implements Serializable
{
	protected int idprojects;

	/** 
	 * This attribute represents whether the primitive attribute idprojects is null.
	 */
	protected boolean idprojectsNull;

	/** 
	 * Sets the value of idprojects
	 */
	public void setIdprojects(int idprojects)
	{
		this.idprojects = idprojects;
	}

	/** 
	 * Gets the value of idprojects
	 */
	public int getIdprojects()
	{
		return idprojects;
	}

	/**
	 * Method 'ProjectsPk'
	 * 
	 */
	public ProjectsPk()
	{
	}

	/**
	 * Method 'ProjectsPk'
	 * 
	 * @param idprojects
	 */
	public ProjectsPk(final int idprojects)
	{
		this.idprojects = idprojects;
	}

	/** 
	 * Sets the value of idprojectsNull
	 */
	public void setIdprojectsNull(boolean idprojectsNull)
	{
		this.idprojectsNull = idprojectsNull;
	}

	/** 
	 * Gets the value of idprojectsNull
	 */
	public boolean isIdprojectsNull()
	{
		return idprojectsNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProjectsPk)) {
			return false;
		}
		
		final ProjectsPk _cast = (ProjectsPk) _other;
		if (idprojects != _cast.idprojects) {
			return false;
		}
		
		if (idprojectsNull != _cast.idprojectsNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idprojects;
		_hashCode = 29 * _hashCode + (idprojectsNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.ProjectsPk: " );
		ret.append( "idprojects=" + idprojects );
		return ret.toString();
	}

}
