/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Projects implements Serializable
{
	/** 
	 * This attribute maps to the column idprojects in the projects table.
	 */
	protected int idprojects;

	/** 
	 * This attribute maps to the column name in the projects table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column description in the projects table.
	 */
	protected String description;

	/** 
	 * This attribute maps to the column start_date in the projects table.
	 */
	protected Date startDate;

	/** 
	 * This attribute maps to the column end_date in the projects table.
	 */
	protected Date endDate;

	/** 
	 * This attribute maps to the column status in the projects table.
	 */
	protected int status;

	/** 
	 * This attribute represents whether the primitive attribute status is null.
	 */
	protected boolean statusNull = true;

	/** 
	 * This attribute maps to the column type in the projects table.
	 */
	protected int type;

	/** 
	 * This attribute represents whether the primitive attribute type is null.
	 */
	protected boolean typeNull = true;

	/** 
	 * This attribute maps to the column company_id in the projects table.
	 */
	protected int companyId;

	/** 
	 * This attribute represents whether the primitive attribute companyId is null.
	 */
	protected boolean companyIdNull = true;

	/** 
	 * This attribute maps to the column branch_id in the projects table.
	 */
	protected int branchId;

	/** 
	 * This attribute represents whether the primitive attribute branchId is null.
	 */
	protected boolean branchIdNull = true;

	/**
	 * Method 'Projects'
	 * 
	 */
	public Projects()
	{
	}

	/**
	 * Method 'getIdprojects'
	 * 
	 * @return int
	 */
	public int getIdprojects()
	{
		return idprojects;
	}

	/**
	 * Method 'setIdprojects'
	 * 
	 * @param idprojects
	 */
	public void setIdprojects(int idprojects)
	{
		this.idprojects = idprojects;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'getStartDate'
	 * 
	 * @return Date
	 */
	public Date getStartDate()
	{
		return startDate;
	}

	/**
	 * Method 'setStartDate'
	 * 
	 * @param startDate
	 */
	public void setStartDate(Date startDate)
	{
		this.startDate = startDate;
	}

	/**
	 * Method 'getEndDate'
	 * 
	 * @return Date
	 */
	public Date getEndDate()
	{
		return endDate;
	}

	/**
	 * Method 'setEndDate'
	 * 
	 * @param endDate
	 */
	public void setEndDate(Date endDate)
	{
		this.endDate = endDate;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return int
	 */
	public int getStatus()
	{
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(int status)
	{
		this.status = status;
		this.statusNull = false;
	}

	/**
	 * Method 'setStatusNull'
	 * 
	 * @param value
	 */
	public void setStatusNull(boolean value)
	{
		this.statusNull = value;
	}

	/**
	 * Method 'isStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isStatusNull()
	{
		return statusNull;
	}

	/**
	 * Method 'getType'
	 * 
	 * @return int
	 */
	public int getType()
	{
		return type;
	}

	/**
	 * Method 'setType'
	 * 
	 * @param type
	 */
	public void setType(int type)
	{
		this.type = type;
		this.typeNull = false;
	}

	/**
	 * Method 'setTypeNull'
	 * 
	 * @param value
	 */
	public void setTypeNull(boolean value)
	{
		this.typeNull = value;
	}

	/**
	 * Method 'isTypeNull'
	 * 
	 * @return boolean
	 */
	public boolean isTypeNull()
	{
		return typeNull;
	}

	/**
	 * Method 'getCompanyId'
	 * 
	 * @return int
	 */
	public int getCompanyId()
	{
		return companyId;
	}

	/**
	 * Method 'setCompanyId'
	 * 
	 * @param companyId
	 */
	public void setCompanyId(int companyId)
	{
		this.companyId = companyId;
		this.companyIdNull = false;
	}

	/**
	 * Method 'setCompanyIdNull'
	 * 
	 * @param value
	 */
	public void setCompanyIdNull(boolean value)
	{
		this.companyIdNull = value;
	}

	/**
	 * Method 'isCompanyIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isCompanyIdNull()
	{
		return companyIdNull;
	}

	/**
	 * Method 'getBranchId'
	 * 
	 * @return int
	 */
	public int getBranchId()
	{
		return branchId;
	}

	/**
	 * Method 'setBranchId'
	 * 
	 * @param branchId
	 */
	public void setBranchId(int branchId)
	{
		this.branchId = branchId;
		this.branchIdNull = false;
	}

	/**
	 * Method 'setBranchIdNull'
	 * 
	 * @param value
	 */
	public void setBranchIdNull(boolean value)
	{
		this.branchIdNull = value;
	}

	/**
	 * Method 'isBranchIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBranchIdNull()
	{
		return branchIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Projects)) {
			return false;
		}
		
		final Projects _cast = (Projects) _other;
		if (idprojects != _cast.idprojects) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		if (startDate == null ? _cast.startDate != startDate : !startDate.equals( _cast.startDate )) {
			return false;
		}
		
		if (endDate == null ? _cast.endDate != endDate : !endDate.equals( _cast.endDate )) {
			return false;
		}
		
		if (status != _cast.status) {
			return false;
		}
		
		if (statusNull != _cast.statusNull) {
			return false;
		}
		
		if (type != _cast.type) {
			return false;
		}
		
		if (typeNull != _cast.typeNull) {
			return false;
		}
		
		if (companyId != _cast.companyId) {
			return false;
		}
		
		if (companyIdNull != _cast.companyIdNull) {
			return false;
		}
		
		if (branchId != _cast.branchId) {
			return false;
		}
		
		if (branchIdNull != _cast.branchIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idprojects;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		if (startDate != null) {
			_hashCode = 29 * _hashCode + startDate.hashCode();
		}
		
		if (endDate != null) {
			_hashCode = 29 * _hashCode + endDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + status;
		_hashCode = 29 * _hashCode + (statusNull ? 1 : 0);
		_hashCode = 29 * _hashCode + type;
		_hashCode = 29 * _hashCode + (typeNull ? 1 : 0);
		_hashCode = 29 * _hashCode + companyId;
		_hashCode = 29 * _hashCode + (companyIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + branchId;
		_hashCode = 29 * _hashCode + (branchIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProjectsPk
	 */
	public ProjectsPk createPk()
	{
		return new ProjectsPk(idprojects);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.Projects: " );
		ret.append( "idprojects=" + idprojects );
		ret.append( ", name=" + name );
		ret.append( ", description=" + description );
		ret.append( ", startDate=" + startDate );
		ret.append( ", endDate=" + endDate );
		ret.append( ", status=" + status );
		ret.append( ", type=" + type );
		ret.append( ", companyId=" + companyId );
		ret.append( ", branchId=" + branchId );
		return ret.toString();
	}

}
