/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ProjectType implements Serializable
{
	/** 
	 * This attribute maps to the column idproject_type in the project_type table.
	 */
	protected int idprojectType;

	/** 
	 * This attribute maps to the column project_type in the project_type table.
	 */
	protected String projectType;

	/** 
	 * This attribute maps to the column branch_id in the project_type table.
	 */
	protected int branchId;

	/** 
	 * This attribute represents whether the primitive attribute branchId is null.
	 */
	protected boolean branchIdNull = true;

	/**
	 * Method 'ProjectType'
	 * 
	 */
	public ProjectType()
	{
	}

	/**
	 * Method 'getIdprojectType'
	 * 
	 * @return int
	 */
	public int getIdprojectType()
	{
		return idprojectType;
	}

	/**
	 * Method 'setIdprojectType'
	 * 
	 * @param idprojectType
	 */
	public void setIdprojectType(int idprojectType)
	{
		this.idprojectType = idprojectType;
	}

	/**
	 * Method 'getProjectType'
	 * 
	 * @return String
	 */
	public String getProjectType()
	{
		return projectType;
	}

	/**
	 * Method 'setProjectType'
	 * 
	 * @param projectType
	 */
	public void setProjectType(String projectType)
	{
		this.projectType = projectType;
	}

	/**
	 * Method 'getBranchId'
	 * 
	 * @return int
	 */
	public int getBranchId()
	{
		return branchId;
	}

	/**
	 * Method 'setBranchId'
	 * 
	 * @param branchId
	 */
	public void setBranchId(int branchId)
	{
		this.branchId = branchId;
		this.branchIdNull = false;
	}

	/**
	 * Method 'setBranchIdNull'
	 * 
	 * @param value
	 */
	public void setBranchIdNull(boolean value)
	{
		this.branchIdNull = value;
	}

	/**
	 * Method 'isBranchIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBranchIdNull()
	{
		return branchIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProjectType)) {
			return false;
		}
		
		final ProjectType _cast = (ProjectType) _other;
		if (idprojectType != _cast.idprojectType) {
			return false;
		}
		
		if (projectType == null ? _cast.projectType != projectType : !projectType.equals( _cast.projectType )) {
			return false;
		}
		
		if (branchId != _cast.branchId) {
			return false;
		}
		
		if (branchIdNull != _cast.branchIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idprojectType;
		if (projectType != null) {
			_hashCode = 29 * _hashCode + projectType.hashCode();
		}
		
		_hashCode = 29 * _hashCode + branchId;
		_hashCode = 29 * _hashCode + (branchIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProjectTypePk
	 */
	public ProjectTypePk createPk()
	{
		return new ProjectTypePk(idprojectType);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.ProjectType: " );
		ret.append( "idprojectType=" + idprojectType );
		ret.append( ", projectType=" + projectType );
		ret.append( ", branchId=" + branchId );
		return ret.toString();
	}

}
