/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the quotes table.
 */
public class QuotesPk implements Serializable
{
	protected int idquotes;

	/** 
	 * This attribute represents whether the primitive attribute idquotes is null.
	 */
	protected boolean idquotesNull;

	/** 
	 * Sets the value of idquotes
	 */
	public void setIdquotes(int idquotes)
	{
		this.idquotes = idquotes;
	}

	/** 
	 * Gets the value of idquotes
	 */
	public int getIdquotes()
	{
		return idquotes;
	}

	/**
	 * Method 'QuotesPk'
	 * 
	 */
	public QuotesPk()
	{
	}

	/**
	 * Method 'QuotesPk'
	 * 
	 * @param idquotes
	 */
	public QuotesPk(final int idquotes)
	{
		this.idquotes = idquotes;
	}

	/** 
	 * Sets the value of idquotesNull
	 */
	public void setIdquotesNull(boolean idquotesNull)
	{
		this.idquotesNull = idquotesNull;
	}

	/** 
	 * Gets the value of idquotesNull
	 */
	public boolean isIdquotesNull()
	{
		return idquotesNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof QuotesPk)) {
			return false;
		}
		
		final QuotesPk _cast = (QuotesPk) _other;
		if (idquotes != _cast.idquotes) {
			return false;
		}
		
		if (idquotesNull != _cast.idquotesNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idquotes;
		_hashCode = 29 * _hashCode + (idquotesNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.QuotesPk: " );
		ret.append( "idquotes=" + idquotes );
		return ret.toString();
	}

}
