/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class StaticProjectPhases implements Serializable
{
	/** 
	 * This attribute maps to the column idstatic_project_phases in the static_project_phases table.
	 */
	protected int idstaticProjectPhases;

	/** 
	 * This attribute maps to the column name in the static_project_phases table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column description in the static_project_phases table.
	 */
	protected String description;

	/** 
	 * This attribute maps to the column type in the static_project_phases table.
	 */
	protected int type;

	/** 
	 * This attribute represents whether the primitive attribute type is null.
	 */
	protected boolean typeNull = true;

	/**
	 * Method 'StaticProjectPhases'
	 * 
	 */
	public StaticProjectPhases()
	{
	}

	/**
	 * Method 'getIdstaticProjectPhases'
	 * 
	 * @return int
	 */
	public int getIdstaticProjectPhases()
	{
		return idstaticProjectPhases;
	}

	/**
	 * Method 'setIdstaticProjectPhases'
	 * 
	 * @param idstaticProjectPhases
	 */
	public void setIdstaticProjectPhases(int idstaticProjectPhases)
	{
		this.idstaticProjectPhases = idstaticProjectPhases;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'getType'
	 * 
	 * @return int
	 */
	public int getType()
	{
		return type;
	}

	/**
	 * Method 'setType'
	 * 
	 * @param type
	 */
	public void setType(int type)
	{
		this.type = type;
		this.typeNull = false;
	}

	/**
	 * Method 'setTypeNull'
	 * 
	 * @param value
	 */
	public void setTypeNull(boolean value)
	{
		this.typeNull = value;
	}

	/**
	 * Method 'isTypeNull'
	 * 
	 * @return boolean
	 */
	public boolean isTypeNull()
	{
		return typeNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StaticProjectPhases)) {
			return false;
		}
		
		final StaticProjectPhases _cast = (StaticProjectPhases) _other;
		if (idstaticProjectPhases != _cast.idstaticProjectPhases) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		if (type != _cast.type) {
			return false;
		}
		
		if (typeNull != _cast.typeNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idstaticProjectPhases;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		_hashCode = 29 * _hashCode + type;
		_hashCode = 29 * _hashCode + (typeNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StaticProjectPhasesPk
	 */
	public StaticProjectPhasesPk createPk()
	{
		return new StaticProjectPhasesPk(idstaticProjectPhases);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.StaticProjectPhases: " );
		ret.append( "idstaticProjectPhases=" + idstaticProjectPhases );
		ret.append( ", name=" + name );
		ret.append( ", description=" + description );
		ret.append( ", type=" + type );
		return ret.toString();
	}

}
