/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Sysusers implements Serializable
{
	/** 
	 * This attribute maps to the column idusers in the sysusers table.
	 */
	protected int idusers;

	/** 
	 * This attribute maps to the column username in the sysusers table.
	 */
	protected String username;

	/** 
	 * This attribute maps to the column password in the sysusers table.
	 */
	protected String password;

	/** 
	 * This attribute maps to the column group_id in the sysusers table.
	 */
	protected int groupId;

	/** 
	 * This attribute represents whether the primitive attribute groupId is null.
	 */
	protected boolean groupIdNull = true;

	/** 
	 * This attribute maps to the column iduser_group in the sysusers table.
	 */
	protected int iduserGroup;

	/** 
	 * This attribute maps to the column name in the sysusers table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column branch_id in the sysusers table.
	 */
	protected int branchId;

	/** 
	 * This attribute represents whether the primitive attribute branchId is null.
	 */
	protected boolean branchIdNull = true;

	/**
	 * Method 'Sysusers'
	 * 
	 */
	public Sysusers()
	{
	}

	/**
	 * Method 'getIdusers'
	 * 
	 * @return int
	 */
	public int getIdusers()
	{
		return idusers;
	}

	/**
	 * Method 'setIdusers'
	 * 
	 * @param idusers
	 */
	public void setIdusers(int idusers)
	{
		this.idusers = idusers;
	}

	/**
	 * Method 'getUsername'
	 * 
	 * @return String
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * Method 'setUsername'
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{
		this.username = username;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'getGroupId'
	 * 
	 * @return int
	 */
	public int getGroupId()
	{
		return groupId;
	}

	/**
	 * Method 'setGroupId'
	 * 
	 * @param groupId
	 */
	public void setGroupId(int groupId)
	{
		this.groupId = groupId;
		this.groupIdNull = false;
	}

	/**
	 * Method 'setGroupIdNull'
	 * 
	 * @param value
	 */
	public void setGroupIdNull(boolean value)
	{
		this.groupIdNull = value;
	}

	/**
	 * Method 'isGroupIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isGroupIdNull()
	{
		return groupIdNull;
	}

	/**
	 * Method 'getIduserGroup'
	 * 
	 * @return int
	 */
	public int getIduserGroup()
	{
		return iduserGroup;
	}

	/**
	 * Method 'setIduserGroup'
	 * 
	 * @param iduserGroup
	 */
	public void setIduserGroup(int iduserGroup)
	{
		this.iduserGroup = iduserGroup;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getBranchId'
	 * 
	 * @return int
	 */
	public int getBranchId()
	{
		return branchId;
	}

	/**
	 * Method 'setBranchId'
	 * 
	 * @param branchId
	 */
	public void setBranchId(int branchId)
	{
		this.branchId = branchId;
		this.branchIdNull = false;
	}

	/**
	 * Method 'setBranchIdNull'
	 * 
	 * @param value
	 */
	public void setBranchIdNull(boolean value)
	{
		this.branchIdNull = value;
	}

	/**
	 * Method 'isBranchIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBranchIdNull()
	{
		return branchIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Sysusers)) {
			return false;
		}
		
		final Sysusers _cast = (Sysusers) _other;
		if (idusers != _cast.idusers) {
			return false;
		}
		
		if (username == null ? _cast.username != username : !username.equals( _cast.username )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (groupId != _cast.groupId) {
			return false;
		}
		
		if (groupIdNull != _cast.groupIdNull) {
			return false;
		}
		
		if (iduserGroup != _cast.iduserGroup) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (branchId != _cast.branchId) {
			return false;
		}
		
		if (branchIdNull != _cast.branchIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idusers;
		if (username != null) {
			_hashCode = 29 * _hashCode + username.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		_hashCode = 29 * _hashCode + groupId;
		_hashCode = 29 * _hashCode + (groupIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + iduserGroup;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + branchId;
		_hashCode = 29 * _hashCode + (branchIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.Sysusers: " );
		ret.append( "idusers=" + idusers );
		ret.append( ", username=" + username );
		ret.append( ", password=" + password );
		ret.append( ", groupId=" + groupId );
		ret.append( ", iduserGroup=" + iduserGroup );
		ret.append( ", name=" + name );
		ret.append( ", branchId=" + branchId );
		return ret.toString();
	}

}
