/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the tasks table.
 */
public class TasksPk implements Serializable
{
	protected int idtasks;

	/** 
	 * This attribute represents whether the primitive attribute idtasks is null.
	 */
	protected boolean idtasksNull;

	/** 
	 * Sets the value of idtasks
	 */
	public void setIdtasks(int idtasks)
	{
		this.idtasks = idtasks;
	}

	/** 
	 * Gets the value of idtasks
	 */
	public int getIdtasks()
	{
		return idtasks;
	}

	/**
	 * Method 'TasksPk'
	 * 
	 */
	public TasksPk()
	{
	}

	/**
	 * Method 'TasksPk'
	 * 
	 * @param idtasks
	 */
	public TasksPk(final int idtasks)
	{
		this.idtasks = idtasks;
	}

	/** 
	 * Sets the value of idtasksNull
	 */
	public void setIdtasksNull(boolean idtasksNull)
	{
		this.idtasksNull = idtasksNull;
	}

	/** 
	 * Gets the value of idtasksNull
	 */
	public boolean isIdtasksNull()
	{
		return idtasksNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TasksPk)) {
			return false;
		}
		
		final TasksPk _cast = (TasksPk) _other;
		if (idtasks != _cast.idtasks) {
			return false;
		}
		
		if (idtasksNull != _cast.idtasksNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idtasks;
		_hashCode = 29 * _hashCode + (idtasksNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.TasksPk: " );
		ret.append( "idtasks=" + idtasks );
		return ret.toString();
	}

}
