/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tasks implements Serializable
{
	/** 
	 * This attribute maps to the column idtasks in the tasks table.
	 */
	protected int idtasks;

	/** 
	 * This attribute maps to the column name in the tasks table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column description in the tasks table.
	 */
	protected String description;

	/** 
	 * This attribute maps to the column start_date in the tasks table.
	 */
	protected Date startDate;

	/** 
	 * This attribute maps to the column end_date in the tasks table.
	 */
	protected Date endDate;

	/** 
	 * This attribute maps to the column phase_id in the tasks table.
	 */
	protected int phaseId;

	/** 
	 * This attribute represents whether the primitive attribute phaseId is null.
	 */
	protected boolean phaseIdNull = true;

	/** 
	 * This attribute maps to the column status in the tasks table.
	 */
	protected int status;

	/** 
	 * This attribute represents whether the primitive attribute status is null.
	 */
	protected boolean statusNull = true;

	/**
	 * Method 'Tasks'
	 * 
	 */
	public Tasks()
	{
	}

	/**
	 * Method 'getIdtasks'
	 * 
	 * @return int
	 */
	public int getIdtasks()
	{
		return idtasks;
	}

	/**
	 * Method 'setIdtasks'
	 * 
	 * @param idtasks
	 */
	public void setIdtasks(int idtasks)
	{
		this.idtasks = idtasks;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'getStartDate'
	 * 
	 * @return Date
	 */
	public Date getStartDate()
	{
		return startDate;
	}

	/**
	 * Method 'setStartDate'
	 * 
	 * @param startDate
	 */
	public void setStartDate(Date startDate)
	{
		this.startDate = startDate;
	}

	/**
	 * Method 'getEndDate'
	 * 
	 * @return Date
	 */
	public Date getEndDate()
	{
		return endDate;
	}

	/**
	 * Method 'setEndDate'
	 * 
	 * @param endDate
	 */
	public void setEndDate(Date endDate)
	{
		this.endDate = endDate;
	}

	/**
	 * Method 'getPhaseId'
	 * 
	 * @return int
	 */
	public int getPhaseId()
	{
		return phaseId;
	}

	/**
	 * Method 'setPhaseId'
	 * 
	 * @param phaseId
	 */
	public void setPhaseId(int phaseId)
	{
		this.phaseId = phaseId;
		this.phaseIdNull = false;
	}

	/**
	 * Method 'setPhaseIdNull'
	 * 
	 * @param value
	 */
	public void setPhaseIdNull(boolean value)
	{
		this.phaseIdNull = value;
	}

	/**
	 * Method 'isPhaseIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isPhaseIdNull()
	{
		return phaseIdNull;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return int
	 */
	public int getStatus()
	{
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(int status)
	{
		this.status = status;
		this.statusNull = false;
	}

	/**
	 * Method 'setStatusNull'
	 * 
	 * @param value
	 */
	public void setStatusNull(boolean value)
	{
		this.statusNull = value;
	}

	/**
	 * Method 'isStatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isStatusNull()
	{
		return statusNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tasks)) {
			return false;
		}
		
		final Tasks _cast = (Tasks) _other;
		if (idtasks != _cast.idtasks) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (description == null ? _cast.description != description : !description.equals( _cast.description )) {
			return false;
		}
		
		if (startDate == null ? _cast.startDate != startDate : !startDate.equals( _cast.startDate )) {
			return false;
		}
		
		if (endDate == null ? _cast.endDate != endDate : !endDate.equals( _cast.endDate )) {
			return false;
		}
		
		if (phaseId != _cast.phaseId) {
			return false;
		}
		
		if (phaseIdNull != _cast.phaseIdNull) {
			return false;
		}
		
		if (status != _cast.status) {
			return false;
		}
		
		if (statusNull != _cast.statusNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idtasks;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		if (description != null) {
			_hashCode = 29 * _hashCode + description.hashCode();
		}
		
		if (startDate != null) {
			_hashCode = 29 * _hashCode + startDate.hashCode();
		}
		
		if (endDate != null) {
			_hashCode = 29 * _hashCode + endDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + phaseId;
		_hashCode = 29 * _hashCode + (phaseIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + status;
		_hashCode = 29 * _hashCode + (statusNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TasksPk
	 */
	public TasksPk createPk()
	{
		return new TasksPk(idtasks);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.Tasks: " );
		ret.append( "idtasks=" + idtasks );
		ret.append( ", name=" + name );
		ret.append( ", description=" + description );
		ret.append( ", startDate=" + startDate );
		ret.append( ", endDate=" + endDate );
		ret.append( ", phaseId=" + phaseId );
		ret.append( ", status=" + status );
		return ret.toString();
	}

}
