/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the user_group table.
 */
public class UserGroupPk implements Serializable
{
	protected int iduserGroup;

	/** 
	 * This attribute represents whether the primitive attribute iduserGroup is null.
	 */
	protected boolean iduserGroupNull;

	/** 
	 * Sets the value of iduserGroup
	 */
	public void setIduserGroup(int iduserGroup)
	{
		this.iduserGroup = iduserGroup;
	}

	/** 
	 * Gets the value of iduserGroup
	 */
	public int getIduserGroup()
	{
		return iduserGroup;
	}

	/**
	 * Method 'UserGroupPk'
	 * 
	 */
	public UserGroupPk()
	{
	}

	/**
	 * Method 'UserGroupPk'
	 * 
	 * @param iduserGroup
	 */
	public UserGroupPk(final int iduserGroup)
	{
		this.iduserGroup = iduserGroup;
	}

	/** 
	 * Sets the value of iduserGroupNull
	 */
	public void setIduserGroupNull(boolean iduserGroupNull)
	{
		this.iduserGroupNull = iduserGroupNull;
	}

	/** 
	 * Gets the value of iduserGroupNull
	 */
	public boolean isIduserGroupNull()
	{
		return iduserGroupNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UserGroupPk)) {
			return false;
		}
		
		final UserGroupPk _cast = (UserGroupPk) _other;
		if (iduserGroup != _cast.iduserGroup) {
			return false;
		}
		
		if (iduserGroupNull != _cast.iduserGroupNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + iduserGroup;
		_hashCode = 29 * _hashCode + (iduserGroupNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.UserGroupPk: " );
		ret.append( "iduserGroup=" + iduserGroup );
		return ret.toString();
	}

}
