/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the users table.
 */
public class UsersPk implements Serializable
{
	protected int idusers;

	/** 
	 * This attribute represents whether the primitive attribute idusers is null.
	 */
	protected boolean idusersNull;

	/** 
	 * Sets the value of idusers
	 */
	public void setIdusers(int idusers)
	{
		this.idusers = idusers;
	}

	/** 
	 * Gets the value of idusers
	 */
	public int getIdusers()
	{
		return idusers;
	}

	/**
	 * Method 'UsersPk'
	 * 
	 */
	public UsersPk()
	{
	}

	/**
	 * Method 'UsersPk'
	 * 
	 * @param idusers
	 */
	public UsersPk(final int idusers)
	{
		this.idusers = idusers;
	}

	/** 
	 * Sets the value of idusersNull
	 */
	public void setIdusersNull(boolean idusersNull)
	{
		this.idusersNull = idusersNull;
	}

	/** 
	 * Gets the value of idusersNull
	 */
	public boolean isIdusersNull()
	{
		return idusersNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UsersPk)) {
			return false;
		}
		
		final UsersPk _cast = (UsersPk) _other;
		if (idusers != _cast.idusers) {
			return false;
		}
		
		if (idusersNull != _cast.idusersNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idusers;
		_hashCode = 29 * _hashCode + (idusersNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.UsersPk: " );
		ret.append( "idusers=" + idusers );
		return ret.toString();
	}

}
