/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Users implements Serializable
{
	/** 
	 * This attribute maps to the column idusers in the users table.
	 */
	protected int idusers;

	/** 
	 * This attribute maps to the column username in the users table.
	 */
	protected String username;

	/** 
	 * This attribute maps to the column password in the users table.
	 */
	protected String password;

	/** 
	 * This attribute maps to the column group_id in the users table.
	 */
	protected int groupId;

	/** 
	 * This attribute represents whether the primitive attribute groupId is null.
	 */
	protected boolean groupIdNull = true;

	/**
	 * Method 'Users'
	 * 
	 */
	public Users()
	{
	}

	/**
	 * Method 'getIdusers'
	 * 
	 * @return int
	 */
	public int getIdusers()
	{
		return idusers;
	}

	/**
	 * Method 'setIdusers'
	 * 
	 * @param idusers
	 */
	public void setIdusers(int idusers)
	{
		this.idusers = idusers;
	}

	/**
	 * Method 'getUsername'
	 * 
	 * @return String
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * Method 'setUsername'
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{
		this.username = username;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'getGroupId'
	 * 
	 * @return int
	 */
	public int getGroupId()
	{
		return groupId;
	}

	/**
	 * Method 'setGroupId'
	 * 
	 * @param groupId
	 */
	public void setGroupId(int groupId)
	{
		this.groupId = groupId;
		this.groupIdNull = false;
	}

	/**
	 * Method 'setGroupIdNull'
	 * 
	 * @param value
	 */
	public void setGroupIdNull(boolean value)
	{
		this.groupIdNull = value;
	}

	/**
	 * Method 'isGroupIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isGroupIdNull()
	{
		return groupIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Users)) {
			return false;
		}
		
		final Users _cast = (Users) _other;
		if (idusers != _cast.idusers) {
			return false;
		}
		
		if (username == null ? _cast.username != username : !username.equals( _cast.username )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (groupId != _cast.groupId) {
			return false;
		}
		
		if (groupIdNull != _cast.groupIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idusers;
		if (username != null) {
			_hashCode = 29 * _hashCode + username.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		_hashCode = 29 * _hashCode + groupId;
		_hashCode = 29 * _hashCode + (groupIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UsersPk
	 */
	public UsersPk createPk()
	{
		return new UsersPk(idusers);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.Users: " );
		ret.append( "idusers=" + idusers );
		ret.append( ", username=" + username );
		ret.append( ", password=" + password );
		ret.append( ", groupId=" + groupId );
		return ret.toString();
	}

}
