/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.pm.app.dal.dto;

import com.pm.app.dal.dao.*;
import com.pm.app.dal.factory.*;
import com.pm.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class WorkingStatus implements Serializable
{
	/** 
	 * This attribute maps to the column idworking_stat in the working_status table.
	 */
	protected int idworkingStat;

	/** 
	 * This attribute maps to the column name in the working_status table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column branch_id in the working_status table.
	 */
	protected int branchId;

	/** 
	 * This attribute represents whether the primitive attribute branchId is null.
	 */
	protected boolean branchIdNull = true;

	/**
	 * Method 'WorkingStatus'
	 * 
	 */
	public WorkingStatus()
	{
	}

	/**
	 * Method 'getIdworkingStat'
	 * 
	 * @return int
	 */
	public int getIdworkingStat()
	{
		return idworkingStat;
	}

	/**
	 * Method 'setIdworkingStat'
	 * 
	 * @param idworkingStat
	 */
	public void setIdworkingStat(int idworkingStat)
	{
		this.idworkingStat = idworkingStat;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getBranchId'
	 * 
	 * @return int
	 */
	public int getBranchId()
	{
		return branchId;
	}

	/**
	 * Method 'setBranchId'
	 * 
	 * @param branchId
	 */
	public void setBranchId(int branchId)
	{
		this.branchId = branchId;
		this.branchIdNull = false;
	}

	/**
	 * Method 'setBranchIdNull'
	 * 
	 * @param value
	 */
	public void setBranchIdNull(boolean value)
	{
		this.branchIdNull = value;
	}

	/**
	 * Method 'isBranchIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBranchIdNull()
	{
		return branchIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof WorkingStatus)) {
			return false;
		}
		
		final WorkingStatus _cast = (WorkingStatus) _other;
		if (idworkingStat != _cast.idworkingStat) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (branchId != _cast.branchId) {
			return false;
		}
		
		if (branchIdNull != _cast.branchIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idworkingStat;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + branchId;
		_hashCode = 29 * _hashCode + (branchIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return WorkingStatusPk
	 */
	public WorkingStatusPk createPk()
	{
		return new WorkingStatusPk(idworkingStat);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.pm.app.dal.dto.WorkingStatus: " );
		ret.append( "idworkingStat=" + idworkingStat );
		ret.append( ", name=" + name );
		ret.append( ", branchId=" + branchId );
		return ret.toString();
	}

}
